spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    topic-name: message-notifications

    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

server:
  port: 8206

#logging:
#    level:
#        org.springframework.kafka: DEBUG
